In [2]:
import numpy as np

In [6]:
# Vytvoření pole (z Pythonovského seznamu
a = np.array([1, 2, 3, 4])

# Vytvoření pole nul s daným tvarem
b = np.zeros((3, 3))

# Vytvoření pole jedniček s daným tvarem
c = np.ones((2, 4))

# Vytvoření pole náhodných čísel s daným tvarem
d = np.random.rand(3, 3)

array([[0.71376773, 0.0499848 , 0.28421609],
       [0.70624006, 0.22722989, 0.24043159],
       [0.51547876, 0.11289273, 0.13775371]])

In [7]:
# Vypsání datového typu
a = np.array([1, 2, 3])
print(a.dtype)

# Změna datového typu
b = a.astype(np.float32)
print(b.dtype)

int64
float32


In [11]:
# Vypsání tvaru
a = np.array([1, 2, 3, 4])
print(a.shape)

# Změna tvaru
b = a.reshape((2, 2))
print(b.shape)
c = np.array([[1, 2], [3, 4]])
print(c.shape)

(4,)
(2, 2)
(2, 2)


In [13]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [15]:
# První řádek
a[0]

array([1, 2, 3])

In [16]:
# Druhý řádek
a[1]

array([4, 5, 6])

In [18]:
# Prvek na prvním řádku, prvním sloupci
a[0, 0]

1

In [20]:
# Prvek na druhém řádku, druhém sloupci
a[1, 1]

5

In [21]:
# Poslední řádek
a[-1]

array([7, 8, 9])

In [40]:
# První sloupec
a[:, 0]

array([1, 4, 7])

In [42]:
# Všechny řádky kromě prvního, všechny sloupce kromě prvního
a[1:, 1:]

array([[5, 6],
       [8, 9]])

In [43]:
# (Všechny řádky), druhý sloupec
a[..., 1]

array([2, 5, 8])

In [32]:
# Prvky na souřadnicích (1, 2), (2, 0)
a[(1, 2), (2, 0)]

array([6, 7])

In [36]:
a[[1, 2], [2, 0]]

array([6, 7])

In [145]:
# První, třetí a druhý řádek
a[[0, 2, 1]]

array([[1, 2, 3],
       [9, 6, 7],
       [4, 8, 5]])

In [51]:
# Přiřazení na pozici
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape((3, 3))
a[0, 1] = 5
a

array([[1, 5, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# Přiřazení sloupce
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape((3, 3))
a[0, :] = 5
a

array([[5, 5, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape((3, 3))
a[0, :] = [5, 3, 4]
a

array([[5, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape((3, 3))
a[0, :] = a[:, 0]
a

array([[1, 4, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape((3, 3))

In [74]:
# Hodnoty větší než pět
a[a > 5]

array([6, 7, 8, 9])

In [76]:
np.where(a > 5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [96]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

In [98]:
# Sečtení dvou polí
a + b

array([3, 5, 7, 9])

In [100]:
# Sečtení pole a čísla
a + 1

array([2, 3, 4, 5])

In [102]:
a * 2

array([2, 4, 6, 8])

In [108]:
# Broadcasting
a = np.array([0, 1, 2]).reshape((1, 3))
b = np.array([0, 1, 2]).reshape((3, 1))
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

![](imgs/broadcast.png)

In [141]:
# np.sum, np.concatenate
a = np.array([
    [1, 2, 3],
    [4, 8, 5],
    [9, 6, 7]
])

In [117]:
np.sum(a)

45

In [118]:
np.sum(a, axis=0)

array([12, 15, 18])

In [128]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [130]:
np.max(a)

9

In [144]:
np.argmax(a, axis=1)

array([[9, 6, 7],
       [4, 8, 5],
       [1, 2, 3]])

In [124]:
np.concatenate([
    a,
    a
], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
np.concatenate([
    a,
    a
], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])